name: calculadora_imc
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  supabase_flutter: ^2.5.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

# Configuração do Ícone do Aplicativo (Corrigido para appimgn.png)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appimgn.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
